# Generated by Django 4.2 on 2024-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_country_course_language_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='course.jpg', null=True, upload_to='course-file'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, default='course.jpg', null=True, upload_to='course-file'),
        ),
    ]
