# Generated by Django 4.2 on 2024-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
