# Generated by Django 4.2 on 2024-01-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_variantitem_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
