# Generated by Django 4.2 on 2024-01-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_variantitem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='content_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
