# Generated by Django 4.2 on 2024-01-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_question_answer_message_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer_message',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.question_answer'),
        ),
    ]
