# Generated by Django 4.2 on 2024-01-27 18:31

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_question_answer_message_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='enrollment_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=20, max_length=50, prefix='ENR'),
        ),
    ]
