# Generated by Django 4.2 on 2024-01-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
