# Generated by Django 4.2 on 2024-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_question_answer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_answer_message',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course-file', verbose_name='Lecture File'),
        ),
    ]
